_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 10

progress_bar_refresh_rate: 5
resume_from_checkpoint: null
weights_summary: "full"
num_sanity_val_steps: 0
gradient_clip_val: 0.5
accumulate_grad_batches: 8
val_check_interval: 0.3
log_every_n_steps: 50
auto_lr_find: True
# auto_scale_batch_size: binsearch # can be `binsearch` or `power`
