_target_: src.models.poet_lightning.PoetLightningModel # Change it later

lr: 0.0001
vocab_size: ???
n_positions: 512
warmup_steps: 0
pretrained_name_or_path: "dkleczek/papuGaPT2" # name of model from HuggingFace model hub
