_target_: poetry_generation.datamodules.emotion_datamodule.EmotionDataModule

tokenizer_path: ${res_dir}/tokenizer/roberta/classification
train_file: ${data_dir}/emotions/cortex/train-emotion.tsv
val_file: ${data_dir}/emotions/cortex/val-emotion.tsv
test_file: ${data_dir}/emotions/cortex/test-emotion.tsv
batch_size: 12
num_workers: 4
pin_memory: True
