_target_: poetry_generation.datamodules.emotion_datamodule.EmotionDatamodule

res_dir: ${res_dir}
tokenizer_path: ${res_dir}/tokenizer/roberta/classification
data_dir: ${data_dir}/cortex
train_path: ${data_dir}/train-emotion.tsv
val_path: ${data_dir}/val-emotion.tsv
test_path: ${data_dir}/test-emotion.tsv
batch_size: 12
num_workers: 4
pin_memory: True
