_target_: poetry_generation.datamodules.stanza_datamodule.StanzaDataModule

tokenizer_path: ${res_dir}/tokenizer/gpt2/generation
data_path: ${data_dir}/poems/stanzas.csv
batch_size: 12
train_val_ratio: 0.8
num_workers: 4
pin_memory: True
